### ISSUE TITLE
feat: suggest adding dropdown for more text-heavy sections

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [sreekaransrinath/sreekaransrinath#16]
### Description
Your README.md file is great and it has loads of information. It was mentioned in a [livestream - Reviewing your Open Source GitHub projects and getting you GREEN squares](https://www.youtube.com/watch?v=ugEJ8LBb1r0) and I would agree with that it would be great to show some of these information when the user needs to see it. Maybe creating a dropdown for the following sections shown in the screenshot below.

### Screenshot
<img width="902" alt="Screen Shot 2021-05-03 at 21 46 11" src="https://user-images.githubusercontent.com/61970868/116912222-fdcb7100-ac58-11eb-97f5-d3398648794e.png">

**Comment by sreekaransrinath** [comment]
Thank you so much for submitting the issue @Rahma-AlWadhahi 😄 
That's some solid advice, I've taken it into consideration in #17
