### ISSUE TITLE
Align the height of GitHub stats and most used languages card

### ISSUE THREAD

**Issue by animeshbhakat** [sreekaransrinath/sreekaransrinath#24]
If you align the height of the GitHub stats and the most used language card then I think it will look much better.

![Screenshot (849)](https://user-images.githubusercontent.com/60314168/118583095-1a67bd00-b7b2-11eb-8b09-60848d3a163c.png)

**Comment by sreekaransrinath** [comment]
Thank you for pointing it out @animeshbhakat; just caught this & fixed with a PR.
